if(NOT ENABLE_SANITIZER_ADDRESS AND NOT ENABLE_SANITIZER_UNDEFINED AND
   NOT ENABLE_SANITIZER_LEAK AND NOT ENABLE_SANITIZER_THREAD AND
   NOT ENABLE_SANITIZER_MEMORY)
  return()
endif()

message(STATUS "=== Sanitizers Configuration ===")
message(STATUS "AddressSanitizer: ${ENABLE_SANITIZER_ADDRESS}")
message(STATUS "UndefinedBehaviorSanitizer: ${ENABLE_SANITIZER_UNDEFINED}")
message(STATUS "LeakSanitizer: ${ENABLE_SANITIZER_LEAK}")
message(STATUS "ThreadSanitizer: ${ENABLE_SANITIZER_THREAD}")
message(STATUS "MemorySanitizer: ${ENABLE_SANITIZER_MEMORY}")
message(STATUS "================================")

if(ENABLE_SANITIZER_THREAD AND
   (ENABLE_SANITIZER_ADDRESS OR ENABLE_SANITIZER_LEAK OR ENABLE_SANITIZER_MEMORY))
  message(FATAL_ERROR
          "ThreadSanitizer cannot be combined with AddressSanitizer, LeakSanitizer, or MemorySanitizer")
endif()
if(ENABLE_SANITIZER_MEMORY AND
   (ENABLE_SANITIZER_ADDRESS OR ENABLE_SANITIZER_LEAK OR ENABLE_SANITIZER_THREAD))
  message(FATAL_ERROR "MemorySanitizer cannot be combined with other sanitizers")
endif()

if(ENABLE_SANITIZER_ADDRESS)
  if(MSVC)
    add_compile_options(/fsanitize=address)
    add_link_options(/fsanitize=address)
  else()
    add_compile_options(-fsanitize=address -fno-omit-frame-pointer
                        -fno-optimize-sibling-calls)
    add_link_options(-fsanitize=address)
  endif()
endif()

if(ENABLE_SANITIZER_UNDEFINED)
  if(MSVC)
    message(WARNING "UndefinedBehaviorSanitizer is not supported by MSVC")
  else()
    add_compile_options(-fsanitize=undefined -fno-omit-frame-pointer)
    add_link_options(-fsanitize=undefined)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      add_compile_options(-fsanitize=integer -fsanitize=nullability)
      add_link_options(-fsanitize=integer -fsanitize=nullability)
    endif()
  endif()
endif()

if(ENABLE_SANITIZER_LEAK)
  if(MSVC)
    message(WARNING "LeakSanitizer is not supported by MSVC")
  else()
    add_compile_options(-fsanitize=leak -fno-omit-frame-pointer)
    add_link_options(-fsanitize=leak)
  endif()
endif()

if(ENABLE_SANITIZER_THREAD)
  if(MSVC)
    message(WARNING "ThreadSanitizer is not supported by MSVC")
  else()
    add_compile_options(-fsanitize=thread -fno-omit-frame-pointer)
    add_link_options(-fsanitize=thread)
  endif()
endif()

if(ENABLE_SANITIZER_MEMORY)
  if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    message(FATAL_ERROR "MemorySanitizer is only supported by Clang")
  endif()
  if(MSVC)
    message(WARNING "MemorySanitizer is not supported by MSVC")
  else()
    add_compile_options(-fsanitize=memory -fno-omit-frame-pointer
                        -fsanitize-memory-track-origins)
    add_link_options(-fsanitize=memory)
  endif()
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug" AND NOT MSVC)
  add_compile_options(-O1 -g)
endif()
